apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-ec-0lmh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/samburrai-tenant/partner-catalog-ec/partner-catalog-ec-0lmh@sha256:138b75f9c81a52272360a5f4e595f5ef87d03710a0cc0b38e55ca28160c563c0
        name: my-java-springboot
        resources: {}
status: {}
