apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-ec-0lmh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/samburrai-tenant/partner-catalog-ec/partner-catalog-ec-0lmh@sha256:79b88b123ae7af842436f15c39661904a7f51f9c5c33a70e2f5e3116edc57759
        name: my-java-springboot
        resources: {}
status: {}
