apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-ec-0lmh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-ec-0lmh
    app.kubernetes.io/part-of: partner-catalog-ec
  name: partner-catalog-ec-0lmh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-ec-0lmh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-ec-0lmh
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/samburrai-tenant/partner-catalog-ec/partner-catalog-ec-0lmh@sha256:09dc69de333ae16987613dd9f7bd3c2f52f49c08f35da685e41932cf910daa8c
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
